/**
 * THE PLAN, AS A DOCUMENT A CUSTOMER CAN BE SENT.
 *
 * Everything on it comes from the plan that was compared — the same figures the
 * screen showed, read through the same presentation rules. Nothing is written
 * for the document alone, so a printed quote can never disagree with the one on
 * screen.
 */

import {
  presentAnnualLimit,
  presentCoreBenefits,
  presentPremium,
  planDocumentFilename,
  type ComparisonPlanResult,
} from '@aggregator/shared';
import { PdfDocument, downloadBlob, rgb, widthOf, wrap } from '@/lib/pdf';

/** The house colours, as the screen uses them. */
const NAVY = rgb(0.1, 0.15, 0.36);
const INK = rgb(0.11, 0.13, 0.2);
const MUTED = rgb(0.42, 0.45, 0.53);
const RULE = rgb(0.85, 0.87, 0.91);
const WASH = rgb(0.96, 0.97, 0.99);

/** A benefit the plan states beyond the six, with whatever it says about it. */
export interface DocumentBenefit {
  name: string;
  value: string | null;
  details: string[];
}

export interface PlanDocumentInput {
  plan: ComparisonPlanResult;
  /** Everything the variant carries that is not one of the six core areas. */
  additional: DocumentBenefit[];
  /** Free text the plan attaches — waiting periods, conditions, exclusions. */
  waitingPeriods: string[];
  conditions: string[];
  exclusions: string[];
  description: string | null;
}

/** A heading with a rule under it, kept with at least one line of its section. */
function section(doc: PdfDocument, title: string) {
  doc.ensure(46);
  doc.y += 10;
  doc.text(title.toUpperCase(), doc.margin, 9, 'bold', MUTED);
  doc.y += 13;
  doc.line(doc.margin, doc.y, doc.width - doc.margin, RULE);
  doc.y += 10;
}

/**
 * A two-column row, label left and value right.
 *
 * The value is measured and the label wrapped to what is left, so a long
 * benefit name pushes itself onto a second line rather than running under the
 * figure.
 */
function row(doc: PdfDocument, label: string, value: string, bold = false) {
  const right = doc.width - doc.margin;
  const valueWidth = widthOf(value, 10, bold ? 'bold' : 'regular');
  const labelWidth = doc.contentWidth - valueWidth - 16;
  const lines = wrap(label, Math.max(labelWidth, 80), 10, 'regular');

  doc.ensure(lines.length * 14 + 4);
  const top = doc.y;
  lines.forEach((line, index) => {
    doc.text(line, doc.margin, 10, 'regular', INK);
    if (index < lines.length - 1) doc.y += 13;
  });
  doc.y = top;
  doc.textRight(value, right, 10, bold ? 'bold' : 'regular', bold ? NAVY : INK);
  doc.y += lines.length * 13 + 5;
  doc.line(doc.margin, doc.y - 3, right, RULE, 0.4);
}

/** Build the document. Returns the blob and the name it should be saved under. */
export function buildPlanDocument(input: PlanDocumentInput): { blob: Blob; filename: string } {
  const { plan } = input;
  const benefits = presentCoreBenefits(plan);

  const doc = new PdfDocument(
    48,
    /**
     * Repeated on every page, so a table that spills over is still headed and
     * a loose second page still says which plan it belongs to.
     */
    (d, page) => {
      d.rect(0, 0, d.width, 4, NAVY);
      d.y = 34;
      d.text('HADBROK', d.margin, 15, 'bold', NAVY);
      d.textRight(
        page === 1 ? 'Plan details' : `${plan.companyName} — ${plan.planName} (continued)`,
        d.width - d.margin,
        9,
        'regular',
        MUTED,
      );
      d.y = 52;
      d.text('Insurance Aggregator', d.margin, 8, 'regular', MUTED);
      d.y = 74;
    },
    (d, page) => {
      d.line(d.margin, d.y - 8, d.width - d.margin, RULE, 0.4);
      d.text('Generated by Hadbrok Insurance Aggregator', d.margin, 8, 'regular', MUTED);
      d.textRight(`Page ${page}`, d.width - d.margin, 8, 'regular', MUTED);
    },
  );

  // --- who and what -------------------------------------------------------
  doc.y += 6;
  doc.text(plan.companyName, doc.margin, 11, 'regular', MUTED);
  doc.y += 16;
  doc.text(plan.planName, doc.margin, 22, 'bold', NAVY);
  doc.y += 28;
  doc.text(
    [plan.customerTypeLabel, plan.geographicalCoverageLabel, plan.currency]
      .filter(Boolean)
      .join('  ·  '),
    doc.margin,
    10,
    'regular',
    MUTED,
  );
  doc.y += 26;

  // --- the two figures a customer reads first ------------------------------
  const half = (doc.contentWidth - 12) / 2;
  doc.rect(doc.margin, doc.y, half, 62, WASH);
  doc.rect(doc.margin + half + 12, doc.y, half, 62, WASH);
  const boxTop = doc.y;
  doc.y += 14;
  doc.text('ANNUAL PREMIUM', doc.margin + 14, 8, 'bold', MUTED);
  doc.text('ANNUAL LIMIT', doc.margin + half + 26, 8, 'bold', MUTED);
  doc.y += 18;
  doc.text(presentPremium(plan), doc.margin + 14, 16, 'bold', NAVY);
  doc.text(presentAnnualLimit(plan), doc.margin + half + 26, 16, 'bold', NAVY);
  doc.y += 20;
  doc.text('per year', doc.margin + 14, 8, 'regular', MUTED);
  doc.text('maximum payable per policy year', doc.margin + half + 26, 8, 'regular', MUTED);
  doc.y = boxTop + 62 + 8;

  if (input.description) {
    section(doc, 'About this plan');
    doc.paragraph(input.description, 10, 'regular', INK);
  }

  // --- the six, always six and always in order -----------------------------
  section(doc, 'Core benefits & coverage');
  for (const benefit of benefits) {
    row(doc, benefit.name, benefit.display, true);
    for (const limitation of benefit.limitations) {
      doc.ensure(12);
      doc.text(`— ${limitation}`, doc.margin + 12, 8.5, 'regular', MUTED);
      doc.y += 12;
    }
  }

  if (input.additional.length) {
    section(doc, 'Additional benefits');
    for (const benefit of input.additional) {
      row(doc, benefit.name, benefit.value ?? 'Covered');
      for (const detail of benefit.details) {
        for (const line of wrap(detail, doc.contentWidth - 16, 8.5, 'regular')) {
          doc.ensure(12);
          doc.text(line, doc.margin + 12, 8.5, 'regular', MUTED);
          doc.y += 11;
        }
      }
    }
  }

  section(doc, 'Plan information');
  row(doc, 'Plan type', plan.customerTypeLabel);
  row(doc, 'Coverage', plan.geographicalCoverageLabel);
  row(doc, 'Currency', plan.currency ?? '—');
  row(doc, 'Annual premium', presentPremium(plan));
  row(doc, 'Annual limit', presentAnnualLimit(plan));
  if (plan.medicalNetworkName) row(doc, 'Medical network', plan.medicalNetworkName);
  if (plan.pricedEmployeeCount !== null) {
    row(doc, 'Employees priced', String(plan.pricedEmployeeCount));
  }

  for (const [title, lines] of [
    ['Waiting periods', input.waitingPeriods],
    ['Conditions', input.conditions],
    ['Exclusions', input.exclusions],
  ] as const) {
    if (!lines.length) continue;
    section(doc, title);
    for (const line of lines) doc.paragraph(line, 9.5, 'regular', INK);
  }

  return {
    blob: doc.build(),
    filename: planDocumentFilename(plan.companyName, plan.planName),
  };
}

/** Build the document and hand it to the browser. */
export function downloadPlanDocument(input: PlanDocumentInput) {
  const { blob, filename } = buildPlanDocument(input);
  downloadBlob(blob, filename);
  return filename;
}
